
package ma.ensa.soap.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NoteBookService", targetNamespace = "http://service.soap.ensa.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NoteBookService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addPerson", targetNamespace = "http://service.soap.ensa.ma/", className = "ma.ensa.soap.service.AddPerson")
    @ResponseWrapper(localName = "addPersonResponse", targetNamespace = "http://service.soap.ensa.ma/", className = "ma.ensa.soap.service.AddPersonResponse")
    @Action(input = "http://service.soap.ensa.ma/NoteBookService/addPersonRequest", output = "http://service.soap.ensa.ma/NoteBookService/addPersonResponse")
    public boolean addPerson(
        @WebParam(name = "arg0", targetNamespace = "")
        Personne arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ma.ensa.soap.service.Personne
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersonAt", targetNamespace = "http://service.soap.ensa.ma/", className = "ma.ensa.soap.service.GetPersonAt")
    @ResponseWrapper(localName = "getPersonAtResponse", targetNamespace = "http://service.soap.ensa.ma/", className = "ma.ensa.soap.service.GetPersonAtResponse")
    @Action(input = "http://service.soap.ensa.ma/NoteBookService/getPersonAtRequest", output = "http://service.soap.ensa.ma/NoteBookService/getPersonAtResponse")
    public Personne getPersonAt(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<ma.ensa.soap.service.Personne>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPersons", targetNamespace = "http://service.soap.ensa.ma/", className = "ma.ensa.soap.service.GetPersons")
    @ResponseWrapper(localName = "getPersonsResponse", targetNamespace = "http://service.soap.ensa.ma/", className = "ma.ensa.soap.service.GetPersonsResponse")
    @Action(input = "http://service.soap.ensa.ma/NoteBookService/getPersonsRequest", output = "http://service.soap.ensa.ma/NoteBookService/getPersonsResponse")
    public List<Personne> getPersons();

}
